import frullImage from './full.png';

export type NoteEntry = {
  key: string;
  asset: string;
  y: number;
  bar?: 'top' | 'middle' | 'bottom';
  sharp?: boolean;
  flat?: boolean;
};

export const noteMap: Record<string, NoteEntry> = {
    36: { key: 'C', asset: frullImage, y: 471, bar: 'middle' },
    '37-sharp': { key: 'C#', sharp: true, asset: frullImage, y: 471, bar: 'middle' },
    '37-flat': { key: 'D♭', flat: true, asset: frullImage, y: 456, bar: 'bottom' },
    38: { key: 'D', asset: frullImage, y: 456, bar: 'bottom' },
    '39-sharp': { key: 'D#', sharp: true, asset: frullImage, y: 456, bar: 'bottom' },
    '39-flat': { key: 'E♭', flat: true, asset: frullImage, y: 440, bar: 'middle' },
    40: { key: 'E', asset: frullImage, y: 440, bar: 'middle' },
    41: { key: 'F', asset: frullImage, y: 425, bar: 'bottom' },
    '42-sharp': { key: 'F#', sharp: true, asset: frullImage, y: 425, bar: 'bottom' },
    '42-flat': { key: 'G♭', flat: true, asset: frullImage, y: 409 },
    43: { key: 'G', asset: frullImage, y: 409 },
    '44-sharp': { key: 'G#', sharp: true, asset: frullImage, y: 409 },
    '44-flat': { key: 'A♭', flat: true, asset: frullImage, y: 394 },
    45: { key: 'A', asset: frullImage, y: 394 },
    '46-sharp': { key: 'A#', sharp: true, asset: frullImage, y: 394 },
    '46-flat': { key: 'B♭', flat: true, asset: frullImage, y: 378 },
    47: { key: 'B', asset: frullImage, y: 378 },
    48: { key: 'C', asset: frullImage, y: 362 },
    '49-sharp': { key: 'C#', sharp: true, asset: frullImage, y: 362 },
    '49-flat': { key: 'D♭', flat: true, asset: frullImage, y: 347 },
    50: { key: 'D', asset: frullImage, y: 347 },
    '51-sharp': { key: 'D#', sharp: true, asset: frullImage, y: 347 },
    '51-flat': { key: 'E♭', flat: true, asset: frullImage, y: 330 },
    52: { key: 'E', asset: frullImage, y: 330 },
    53: { key: 'F', asset: frullImage, y: 315 },
    '54-sharp': { key: 'F#', sharp: true, asset: frullImage, y: 315 },
    '54-flat': { key: 'G♭', flat: true, asset: frullImage, y: 300 },
    55: { key: 'G', asset: frullImage, y: 300 },
    '56-sharp': { key: 'G#', sharp: true, asset: frullImage, y: 300 },
    '56-flat': { key: 'A♭', flat: true, asset: frullImage, y: 284 },
    57: { key: 'A', asset: frullImage, y: 284 },
    '58-sharp': { key: 'A#', sharp: true, asset: frullImage, y: 284 },
    '58-flat': { key: 'B♭', flat: true, asset: frullImage, y: 268 },
    59: { key: 'B', asset: frullImage, y: 268 },
    60: { key: 'C', asset: frullImage, y: 198, bar: 'middle' },
    '61-sharp': { key: 'C#', sharp: true, asset: frullImage, y: 198, bar: 'middle' },
    '61-flat': { key: 'D♭', flat: true, asset: frullImage, y: 179 },
    62: { key: 'D', asset: frullImage, y: 179 },
    '63-sharp': { key: 'D#', sharp: true, asset: frullImage, y: 179 },
    '63-flat': { key: 'E♭', flat: true, asset: frullImage, y: 165 },
    64: { key: 'E', asset: frullImage, y: 165 },
    65: { key: 'F', asset: frullImage, y: 148 },
    '66-sharp': { key: 'F#', sharp: true, asset: frullImage, y: 148 },
    '66-flat': { key: 'G♭', flat: true, asset: frullImage, y: 132 },
    67: { key: 'G', asset: frullImage, y: 132 },
    '68-sharp': { key: 'G#', sharp: true, asset: frullImage, y: 132 },
    '68-flat': { key: 'A♭', flat: true, asset: frullImage, y: 116 },
    69: { key: 'A', asset: frullImage, y: 116 },
    '70-sharp': { key: 'A#', sharp: true, asset: frullImage, y: 116 },
    '70-flat': { key: 'B♭', flat: true, asset: frullImage, y: 100 },
    71: { key: 'B', asset: frullImage, y: 100 },
    72: { key: 'C', asset: frullImage, y: 85 },
    '73-sharp': { key: 'C#', sharp: true, asset: frullImage, y: 85 },
    '73-flat': { key: 'D♭', flat: true, asset: frullImage, y: 69 },
    74: { key: 'D', asset: frullImage, y: 69 },
    '75-sharp': { key: 'D#', sharp: true, asset: frullImage, y: 69 },
    '75-flat': { key: 'E♭', flat: true, asset: frullImage, y: 55 },
    76: { key: 'E', asset: frullImage, y: 55 },
    77: { key: 'F', asset: frullImage, y: 39 },
    '78-sharp': { key: 'F#', sharp: true, asset: frullImage, y: 39 },
    '78-flat': { key: 'G♭', flat: true, asset: frullImage, y: 23, bar: 'top' },
    79: { key: 'G', asset: frullImage, y: 23, bar: 'top' },
    '80-sharp': { key: 'G#', sharp: true, asset: frullImage, y: 23, bar: 'top' },
    '80-flat': { key: 'A♭', flat: true, asset: frullImage, y: 8, bar: 'middle' },
    81: { key: 'A', asset: frullImage, y: 8, bar: 'middle' },
    '82-sharp': { key: 'A#', sharp: true, asset: frullImage, y: 8, bar: 'middle' },
    '82-flat': { key: 'B♭', flat: true, asset: frullImage, y: -8, bar: 'top' },
    83: { key: 'B', asset: frullImage, y: -8, bar: 'top' },
    84: { key: 'C', asset: frullImage, y: -23, bar: 'middle' },
};

